/**
 * build.mjs — bundles src/ into dist/, which IS the unpacked extension folder.
 *
 * Chrome content scripts cannot use ES modules when declared in the manifest,
 * and MV3 service workers cannot use importScripts() when type=module. Bundling
 * sidesteps both, and it is the mechanism that will later let us pull in
 * Playwright's injected selector engine from vendor/ as a pinned artifact.
 *
 *   npm run build     one-shot
 *   npm run watch     rebuild on change
 */
import { build, context, transform } from 'esbuild';
import { cpSync, rmSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = dirname(fileURLToPath(import.meta.url));
const out = resolve(root, 'dist');
const watch = process.argv.includes('--watch');

const ENTRIES = {
  // Injected into every frame of the recorded tab.
  'content': resolve(root, 'src/core/content/index.js'),
  // MV3 service worker.
  'background': resolve(root, 'src/core/background/index.js'),
  // Extension popup.
  'popup': resolve(root, 'src/ui/popup/popup.js'),
};

const options = {
  entryPoints: ENTRIES,
  outdir: out,
  bundle: true,
  format: 'iife',        // content scripts must not be modules
  target: 'chrome110',
  platform: 'browser',
  sourcemap: watch ? 'inline' : false,
  minify: !watch,
  legalComments: 'none',
  logLevel: 'info',
};

function copyStatic() {
  // public/ holds everything that ships verbatim: manifest, icons, HTML, CSS.
  cpSync(resolve(root, 'public'), out, { recursive: true });
}

// ── Playwright's injected selector engine ───────────────────────────────────
//
// Emitted as its own bundle, deliberately NOT listed in manifest content_scripts.
// It is ~180 KB minified; declaring it as a content script would parse and run
// it in every frame of every page the user visits, whether or not they are
// recording. It is injected on demand (chrome.scripting.executeScript) when
// recording starts, which is the only moment it is worth its weight.
//
// The bootstrap is intentionally tiny: define a CommonJS `module` binding, run
// the vendored bundle inside it, then instantiate. `module.exports.InjectedScript`
// is a lazy getter thunk produced by esbuild's __toCommonJS — it must be CALLED
// to yield the class, hence `module.exports.InjectedScript()`.
const VENDOR_JS = resolve(root, 'vendor/playwright/injected-script.js');
const VENDOR_VERSION = resolve(root, 'vendor/playwright/VERSION');
const GLOBAL_NAME = '__flowtracePwInjected';

function ensureVendored() {
  if (existsSync(VENDOR_JS) && existsSync(VENDOR_VERSION)) {
    const vendored = readFileSync(VENDOR_VERSION, 'utf8').trim();
    const installed = JSON.parse(
      readFileSync(resolve(root, 'node_modules/playwright-core/package.json'), 'utf8'),
    ).version;
    if (vendored !== installed) {
      // Not fatal — but a silent mismatch means shipping selectors generated by
      // a version nobody has looked at.
      console.warn(
        `[build] vendor/playwright is from playwright-core@${vendored} but ` +
        `${installed} is installed — run \`npm run vendor\``,
      );
    }
    return;
  }
  console.log('[build] vendor/playwright missing — extracting');
  execFileSync(process.execPath, [resolve(root, 'scripts/vendor-injected.mjs')], {
    stdio: 'inherit',
  });
}

async function buildSelectorEngine() {
  ensureVendored();
  const injected = readFileSync(VENDOR_JS, 'utf8');
  const source = [
    '(() => {',
    `  if (globalThis.${GLOBAL_NAME}) return;`,
    '  const module = { exports: {} };',
    '  const exports = module.exports;',
    injected,
    // NOT named `InjectedScript`: the vendored bundle declares a class by that
    // name in this same scope, and a `const` shadowing it is a redeclaration.
    '  const Ctor = module.exports.InjectedScript();',
    `  globalThis.${GLOBAL_NAME} = new Ctor(globalThis, {`,
    '    isUnderTest: false,',
    "    sdkLanguage: 'javascript',",
    '    frameSeq: 0,',
    "    testIdAttributeName: 'data-testid',",
    '    stableRafCount: 1,',
    "    browserName: 'chromium',",
    '    shouldPrependErrorPrefix: false,',
    '    isUtilityWorld: false,',
    '    customEngines: [],',
    '  });',
    '})();',
  ].join('\n');

  const code = watch
    ? source
    : (await transform(source, {
        minify: true,
        target: options.target,
        legalComments: 'none',
      })).code;

  writeFileSync(resolve(out, 'selector-engine.js'), code, 'utf8');
  console.log(
    `[build] dist/selector-engine.js  ${(Buffer.byteLength(code) / 1024).toFixed(1)}kb  ` +
    '(injected on demand, not a content script)',
  );
}

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
copyStatic();
await buildSelectorEngine();

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('[build] watching — load dist/ as an unpacked extension');
} else {
  await build(options);
  console.log('[build] dist/ ready — load it as an unpacked extension');
}
