/**
 * compiler.js — processed events → an executable Playwright script and the
 * step array the replayer consumes.
 *
 * The compiler is application-agnostic on purpose. By the time events reach it,
 * a patch's postProcess has already rewritten anything product-specific, so the
 * only decisions left are mechanical ones about statement shape.
 *
 * Where an event needs a value other than the one typed — because the
 * application normalised it after the fact — the patch sets `committedValue`,
 * and the compiler prefers it. That keeps a generic field name in the core
 * rather than the compiler reaching into a patch-specific map.
 */

import { CREDENTIAL_REF, isSensitiveEvent } from '../shared/sensitive.js';
import { isLocatorlessVerb, pruneLocator } from '../shared/schema.js';
import { attributeSelector, jsString } from '../content/escape.js';
import { idSelector } from '../content/escape.js';
import { isStableId } from '../content/selector.js';

/**
 * @param {Object[]} events
 * @param {Object} session
 * @param {{name: string, id: string, version: string}} patchMeta
 * @returns {string}
 */
export function compileScript(events, session, patchMeta) {
  if (!events || events.length === 0) return '// No events recorded yet.';

  const lines = [
    '// ================================================================',
    '// Generated by FlowTrace Recorder',
    `// Patch       : ${patchMeta.name} (${patchMeta.id} v${patchMeta.version})`,
    `// Recorded    : ${new Date().toISOString()}`,
    `// Source URL  : ${session.sourceUrl || 'unknown'}`,
    `// Raw events  : ${session.events.length}`,
    `// Processed   : ${events.length}`,
    '// ================================================================',
    '',
    "const { chromium } = require('playwright');",
    '',
    '(async () => {',
    '  const browser = await chromium.launch({ headless: false });',
    '  const context = await browser.newContext();',
    '  const page    = await context.newPage();',
    '',
  ];

  let previousUrl = null;
  for (const event of events) {
    const statement = toStatement(event, previousUrl);
    if (!statement) continue;
    lines.push(`  ${statement}`);
    if (event.type === 'navigate') previousUrl = event.url;
  }

  lines.push('', '  await browser.close();', '})();');
  return lines.join('\n');
}

/** The structured form the replayer executes. */
export function compileSteps(events) {
  if (!events || events.length === 0) return [];

  const steps = [];
  let previousUrl = null;

  for (const event of events) {
    const statement = toStatement(event, previousUrl);
    if (!statement) continue;

    steps.push({
      type: 'code',
      code: statement.replace(/^await\s+/, '').replace(/;$/, ''),
      rawCode: statement,
      // Frame identity travels with the step as well as being compiled into
      // `code` above, because the replayer resolves the frame from `frame.url`
      // and never parses the string. `name` is omitted rather than written as
      // an explicit null: a null reads as "this frame has no name", where
      // absent reads as "nothing addressable was found", which is what
      // frameIdentity() actually reports.
      ...(event.isTopFrame === false
        ? {
          frame: {
            url: event.frameUrl,
            ...(event.frameName ? { name: event.frameName } : {}),
          },
        }
        : {}),
      ...(event.required !== undefined
        ? {
          required: event.required,
          requiredSource: event.requiredSource,
          ...(event.requiredScope ? { requiredScope: event.requiredScope } : {}),
        }
        : {}),
      ...(event.committedValue != null ? { committedValue: event.committedValue } : {}),
      ...(event.originalValue !== undefined ? { originalValue: event.originalValue } : {}),
      ...(event.value !== undefined ? { value: event.value } : {}),
    });

    if (event.type === 'navigate') previousUrl = event.url;
  }
  return steps;
}

// ── Structured actions ──────────────────────────────────────────────────────
//
// The replayer does not run the generated script. It reads an ACTION list and
// resolves each step against the live page, trying every locator the recorder
// captured in turn (engine/locators.ts `candidatesFor`). A code string is a
// single locator with the fallbacks thrown away, so `actions` — not `steps` —
// is what a replay should be driven from. Both are emitted: the script remains
// the artefact a human reads and edits.

/**
 * Recorder event types that already spell an action the replayer handles.
 * Keyed lowercase; the value is the exact spelling from the verb enum (the
 * replayer lowercases before dispatch, but the report prints what we write).
 *
 * The verbs that need a field of their own — fill, press, select, check — are
 * handled explicitly in `toAction`; everything here is either bare or carries
 * only fields that are safe to read off the event unconditionally.
 */
const DIRECT_ACTIONS = {
  click: 'click',
  dblclick: 'dblclick',
  hover: 'hover',
  copy: 'copy',
  lovselect: 'lovSelect',
  setinputfiles: 'setInputFiles',
  assertvisible: 'assertVisible',
  asserttext: 'assertText',
  assertvalue: 'assertValue',
  assertchecked: 'assertChecked',
  assertsnapshot: 'assertSnapshot',
};

/** Which of the direct verbs above take a `value`. */
const VALUE_ACTIONS = new Set(['lovSelect', 'assertText', 'assertValue']);

/** How long a wait pauses for when the event did not say. */
const DEFAULT_WAIT_MS = 1000;

/**
 * The structured form the replayer executes.
 *
 * @param {Object[]} events  post-processed events
 * @returns {Object[]}
 */
export function compileActions(events) {
  if (!events || events.length === 0) return [];

  const actions = [];
  let previousUrl = null;

  for (const event of events) {
    const action = toAction(event, previousUrl);
    if (!action) continue;
    actions.push(action);
    if (event.type === 'navigate') previousUrl = event.url;
  }
  return actions;
}

function toAction(event, previousUrl) {
  const type = String(event.type || '').toLowerCase();
  const meta = event.meta || {};

  if (type === 'navigate') {
    if (!event.url || event.url === previousUrl) return null;
    return element('navigate', event, { url: event.url });
  }

  if (type === 'fill') {
    // The application's own normalisation wins over the keystrokes, exactly as
    // it does in the generated script.
    const committed = event.committedValue ?? meta.committedValue;
    return element('fill', event, {
      value: committed != null ? committed : (event.value ?? ''),
      committedValue: committed,
      // Carried so the replayer can put a real credential back at run time.
      // Without it the replay types the literal mask into the password box and
      // fails at the sign-in with no indication why.
      sensitive: isSensitiveEvent(event) || undefined,
      credentialRef: isSensitiveEvent(event) ? (event.credentialRef || CREDENTIAL_REF) : undefined,
    });
  }

  if (type === 'select') {
    // The bare verb `select` is retired because it named two different
    // interactions. `selectOption` drives a real <select>; `lovSelect` picks a
    // row out of a list that is already open, which is performed as a click.
    // Conflated, the replayer opened the dropdown and chose nothing.
    const label = meta.optionLabel ?? event.value;
    return meta.selectByClick
      ? element('lovSelect', event, { value: label })
      : element('selectOption', event, { value: label, optionIndex: meta.optionIndex });
  }

  if (type === 'check' || type === 'radio') {
    const name = type === 'radio' || event.checked !== false ? 'check' : 'uncheck';
    return element(name, event, { checked: name === 'check' });
  }

  if (type === 'press') {
    // postProcess synthesises Tab presses with the key in `value`.
    return element('press', event, { key: event.key || event.value || 'Tab' });
  }

  if (type === 'scroll') {
    return element('scroll', event, { deltaX: event.deltaX, deltaY: event.deltaY });
  }

  if (type === 'wait') {
    // Explicit numeric durationMs ensures deterministic pauses across replay runs.
    return element('wait', event, { durationMs: waitDuration(event) });
  }

  const direct = DIRECT_ACTIONS[type];
  if (direct) {
    return element(direct, event, {
      value: VALUE_ACTIONS.has(direct) ? event.value ?? undefined : undefined,
      checked: direct === 'assertChecked' ? event.checked : undefined,
      outputName: direct === 'copy' ? (event.outputName ?? meta.outputName) : undefined,
      files: direct === 'setInputFiles' ? event.files : undefined,
      snapshot: direct === 'assertSnapshot' ? event.snapshot : undefined,
    });
  }

  // Patch-private bookkeeping (meta_*). The compiler drops what it does not
  // recognise rather than guessing: the replayer refuses an unknown action
  // outright, so guessing here would fail the whole run at replay time.
  return null;
}

/** The pause a wait asks for, in milliseconds. */
function waitDuration(event) {
  const raw = event.durationMs ?? event.value ?? event.text;
  const ms = Number(raw);
  return Number.isFinite(ms) && ms > 0 ? ms : DEFAULT_WAIT_MS;
}

/**
 * Assemble one action element.
 *
 * Empty fields are omitted rather than written as null. `skipInReport` is the
 * exception — the replayer reads it as a boolean and the report filters on it,
 * so it is always present and always a boolean.
 */
function element(action, event, extra = {}) {
  const meta = event.meta || {};
  const out = { action };

  // navigate / wait / scroll act on the page, so they carry no locator at all.
  // An empty object would read as "an element was captured and every field of
  // it was blank", which is a different and much worse claim.
  if (!isLocatorlessVerb(action)) {
    const locator = locatorObjectFor(event);
    if (Object.keys(locator).length) out.locator = locator;
  }

  out.skipInReport = !!(event.skipInReport ?? meta.skipInReport);

  const description = event.description ?? meta.description;
  if (description) out.description = description;

  const req = event.required ?? meta.required;
  if (req !== undefined && req !== null) {
    out.required = req;
    const reqSource = event.requiredSource ?? meta.requiredSource;
    if (reqSource) out.requiredSource = reqSource;
    const reqScope = event.requiredScope ?? meta.requiredScope;
    if (reqScope) out.requiredScope = reqScope;
  }

  for (const [key, value] of Object.entries(extra)) {
    if (value === undefined || value === null) continue;
    out[key] = value;
  }

  // Frame identity travels with the action, and the replayer routes on it:
  // engine/frames.ts `resolveScope` polls for the frame and matches name → id
  // → title, or by URL path. It throws when the frame is absent rather than
  // falling back to the top document, because the top frame routinely holds a
  // control with the same accessible name.
  if (event.isTopFrame === false) {
    out.frame = { url: event.frameUrl };
    if (event.frameName) out.frame.name = event.frameName;
  }
  return out;
}

/**
 * The RecordedLocator for an event.
 *
 * Normally the content script already built one against the live element —
 * that is the rich version, and nothing here can reconstruct what it saw. This
 * rebuilds a usable subset from the flat event fields for the two cases where
 * there is no object: an event a patch's postProcess synthesised in the service
 * worker, and a recording made before locator objects existed.
 */
function locatorObjectFor(event) {
  const meta = event.meta || {};
  const built = event.locatorObject && typeof event.locatorObject === 'object'
    ? { ...event.locatorObject }
    : fromFlatEvent(event, meta);

  // postProcess rewrites `selector` on the event; keep the object in step with
  // it, otherwise the replayer tries a selector the patch already rejected.
  if (event.selector && !built.selector) built.selector = event.selector;

  // The allow-list is applied HERE rather than trusted from upstream: a patch's
  // postProcess merges arbitrary fields into `locatorObject`, and this is the
  // last point before the object is stored and shipped.
  return pruneLocator(built);
}

function fromFlatEvent(event, meta) {
  const label = event.label || meta.resolvedLabel || meta.ariaLabel || '';
  const text = event.text || meta.resolvedText || '';
  return {
    id: meta.id || undefined,
    role: event.role || meta.resolvedRole || meta.role || undefined,
    name: label || text || meta.title || undefined,
    label: label || undefined,
    title: meta.title || undefined,
    text: text || undefined,
    selector: event.selector || undefined,
    attrSelector: attrSelectorFromMeta(meta),
    placeholder: meta.placeholder || undefined,
    sourceTag: event.tagName || undefined,
    componentId: meta.componentId || undefined,
    containerRole: meta.containerRole || undefined,
    hasLovIcon: meta.hasLovIcon === true ? true : undefined,
  };
}

/** Same order as the content script's, so both paths agree on which attribute wins. */
const META_ATTR_ORDER = [
  ['data-testid', 'data-testid'], ['data-test', 'data-test'],
  ['data-qa', 'data-qa'], ['data-cy', 'data-cy'],
  ['title', 'title'], ['aria-label', 'ariaLabel'],
  ['name', 'name'], ['placeholder', 'placeholder'],
];

function attrSelectorFromMeta(meta) {
  for (const [attr, key] of META_ATTR_ORDER) {
    if (meta[key]) return attributeSelector(attr, meta[key]);
  }
  return undefined;
}

function toStatement(event, previousUrl) {
  switch (event.type) {
    case 'navigate':
      return event.url === previousUrl ? null : `await page.goto(${jsString(event.url)});`;

    case 'click': {
      const locator = locatorFor(event);
      return locator ? `await ${locator}.click();` : null;
    }

    case 'fill': {
      const locator = locatorFor(event);
      if (!locator) return null;
      const value = event.committedValue != null ? event.committedValue : event.value;
      return `await ${locator}.fill(${jsString(value ?? '')});`;
    }

    case 'select': {
      const locator = locatorFor(event);
      if (!locator) return null;
      // Some controls are a listbox in name only: the patch has already pointed
      // the locator at the option row, so clicking it is the correct action.
      if (event.meta?.selectByClick) return `await ${locator}.click();`;
      const option = event.meta?.optionLabel ?? event.value;
      return `await ${locator}.selectOption(${jsString(option)});`;
    }

    case 'check': {
      const locator = locatorFor(event);
      if (!locator) return null;
      return event.checked ? `await ${locator}.check();` : `await ${locator}.uncheck();`;
    }

    case 'radio': {
      const locator = locatorFor(event);
      return locator ? `await ${locator}.check();` : null;
    }

    default:
      // Patch-private bookkeeping events (meta_*) reach here when postProcess
      // has consumed them. Emitting nothing is the correct outcome.
      return null;
  }
}

/**
 * Choose the locator expression for an event, rooted in the frame it happened
 * in.
 *
 * Frame scoping is applied here rather than at each call site because every
 * element-bearing statement goes through this function — the same reason the
 * replayer threads scope through `candidatesFor` alone.
 */
function locatorFor(event) {
  return scopeToFrame(locatorExpression(event), event);
}

/**
 * Re-root a `page.…` expression at the frame the event was recorded in.
 *
 * `frameIdentity()` in content/frames.js reports whichever of `name`, `title`
 * or `id` the frame element carried, and does not say which one it found. The
 * replayer resolves the same ambiguity by trying all three (frames.ts matches
 * name → id → title), so the generated script states it as a selector list
 * rather than guessing one attribute and being wrong two thirds of the time.
 *
 * A frame with no addressable attribute yields no scope: `frameIdentity()`
 * already returned null, and inventing a positional `nth()` here would be a
 * guess that reads as fact. The unscoped expression is left alone — the v1
 * action still carries `frame.url`, which is what the replayer actually
 * resolves; this string is the artefact a human reads.
 */
function scopeToFrame(expression, event) {
  if (!expression || event.isTopFrame !== false) return expression;
  const name = event.frameName;
  if (!name) return expression;
  const selector = ['name', 'title', 'id']
    .map((attr) => `iframe[${attr}="${name}"]`)
    .join(', ');
  return expression.replace(/^page\./, `page.frameLocator(${jsString(selector)}).`);
}

/**
 * The locator expression itself, before frame scoping.
 *
 * The content script already generated one. This exists because a patch's
 * postProcess may have changed `role`, `label` or `text` after the fact, in
 * which case the recorded expression is stale and must be rebuilt.
 */
function locatorExpression(event) {
  // A patch that set a complete expression wins outright.
  if (event.locator && event.locator.startsWith('page.')) return event.locator;

  const meta = event.meta || {};

  if (meta.id && isStableId(meta.id)) {
    return `page.locator(${jsString(idSelector(meta.id))})`;
  }
  for (const attr of ['data-testid', 'data-test', 'data-qa', 'data-cy']) {
    if (meta[attr]) return `page.locator(${jsString(`[${attr}="${meta[attr]}"]`)})`;
  }
  if (meta.ariaLabel) return `page.getByLabel(${jsString(meta.ariaLabel)})`;
  if (event.label) return `page.getByLabel(${jsString(event.label)})`;
  if (event.role && event.text) {
    return `page.getByRole(${jsString(event.role)}, { name: ${jsString(event.text)} })`;
  }
  if (meta.name) return `page.locator(${jsString(`[name="${meta.name}"]`)})`;
  if (meta.placeholder) return `page.getByPlaceholder(${jsString(meta.placeholder)})`;
  if (event.selector) return `page.locator(${jsString(event.selector)})`;

  return null;
}
